# Generated by Django 4.2.6 on 2023-10-21 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="posted",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2023, 10, 21, 13, 13, 41, 366802),
                verbose_name="Опубликована",
            ),
        ),
    ]
